version: "3.9"

services:
  redis_db:
    image: redis:latest
    container_name: redis_py_db
    ports:
      - "6379:6379"

  pg_db:
    image: postgres:latest
    restart: always
    container_name: pg_py_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pyauthdb
      - POSTGRES_USER=tyler
      - POSTGRES_PASSWORD=thefightclub